include         /usr/local/Cellar/openldap/2.7.0/.bottle/etc/openldap/schema/core.schema
include         /usr/local/Cellar/openldap/2.7.0/.bottle/etc/openldap/schema/cosine.schema
include         /usr/local/Cellar/openldap/2.7.0/.bottle/etc/openldap/schema/inetorgperson.schema
include         /Users/abc/Downloads/LDAP_Server/ldap-phonebook-webapp/ldap-local/etc/schema/phone2schema.schema

pidfile         /Users/abc/Downloads/LDAP_Server/ldap-phonebook-webapp/ldap-local/run/slapd.pid
argsfile        /Users/abc/Downloads/LDAP_Server/ldap-phonebook-webapp/ldap-local/run/slapd.args

modulepath      /usr/local/opt/openldap/libexec/openldap
moduleload      back_mdb.la

database        mdb
maxsize         1073741824
suffix          "dc=coreip,dc=local"
rootdn          "cn=admin,dc=coreip,dc=local"
rootpw          {SSHA}s4ZVdymADnGiYGiYjuupJcr8aD+yKBCn
directory       /Users/abc/Downloads/LDAP_Server/ldap-phonebook-webapp/ldap-local/data

index           objectClass eq

database        monitor
